Import libraries and all the data we got by email

In [1]:
import numpy as np
from numpy.linalg import inv

In [2]:
# our ciphertext
cipher = [0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1]

# matrix G, S, H, P
G = np.array([[0, 1, 1, 0, 0, 1, 0],
              [1, 1, 0, 1, 0, 0, 0],
              [0, 0, 1, 0, 1, 1, 1],
              [1, 0, 1, 0, 0, 0, 1]])

H = np.array([[0, 1, 1],
              [1, 0, 0],
              [0, 0, 1],
              [1, 1, 1],
              [1, 1, 0],
              [1, 0, 1],
              [0, 1, 0]])

S = np.array([[0, 0, 0, 1],
              [1, 0, 0, 1],
              [1, 0, 1, 1],
              [0, 1, 0, 0]])


P = np.array([
    [0, 0, 0, 0, 0, 0, 1],
    [0, 1, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0],
    [0, 0, 0, 1, 0, 0, 0],
    [1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 0]
])



Divide the cipher text into n-bit vectors

In [3]:
n = 7
y = [cipher[i:i+n] for i in range(0, len(cipher), n)]
print("\n We devided our string into 7-bit vectors y: \n")
print(y)

# convert each y_i to a matrix
y_matrices = [list(map(int, list(vector))) for vector in y]


print("\n Here are all the vectors: \n")
# print the result
for i, vector in enumerate(y_matrices, start=1):
    print(f"y{i}: {vector}")


 We devided our string into 7-bit vectors y: 

[[0, 1, 0, 1, 0, 0, 1], [0, 1, 1, 1, 1, 0, 1], [0, 1, 0, 1, 0, 0, 0], [0, 1, 0, 1, 0, 1, 1], [1, 1, 0, 0, 1, 1, 1], [0, 1, 0, 1, 0, 0, 1], [0, 1, 1, 1, 1, 0, 0], [0, 1, 1, 1, 0, 1, 1], [0, 1, 1, 1, 1, 1, 0], [0, 0, 1, 1, 0, 0, 1], [1, 1, 1, 0, 1, 1, 1], [1, 1, 1, 1, 0, 0, 1]]

 Here are all the vectors: 

y1: [0, 1, 0, 1, 0, 0, 1]
y2: [0, 1, 1, 1, 1, 0, 1]
y3: [0, 1, 0, 1, 0, 0, 0]
y4: [0, 1, 0, 1, 0, 1, 1]
y5: [1, 1, 0, 0, 1, 1, 1]
y6: [0, 1, 0, 1, 0, 0, 1]
y7: [0, 1, 1, 1, 1, 0, 0]
y8: [0, 1, 1, 1, 0, 1, 1]
y9: [0, 1, 1, 1, 1, 1, 0]
y10: [0, 0, 1, 1, 0, 0, 1]
y11: [1, 1, 1, 0, 1, 1, 1]
y12: [1, 1, 1, 1, 0, 0, 1]


Compute y_1 = yP^-1

In [4]:
# inverse of matrix P
P_inv = inv(P) % 2

print("\n P inverse:")
print(P_inv)


# calculate y_1 = y * P^(-1) for each y_i
y1_matrices = [np.dot(y_matrix, P_inv) for y_matrix in y_matrices]
print("\n We calculated y_1 = y * P^(-1) for each y_i: \n")
print(y1_matrices)

# convert the result back to binary strings
y1_binary_strings = [''.join(map(str, y1_matrix.flatten().astype(int))) for y1_matrix in y1_matrices]

print("\n And here is a binary string for each vector: \n")
# print the result
for i, y1_binary_string in enumerate(y1_binary_strings, start=1):
    print(f"y{i}_1: {y1_binary_string}")



 P inverse:
[[0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0.]]

 We calculated y_1 = y * P^(-1) for each y_i: 

[array([1., 1., 0., 0., 1., 0., 0.]), array([1., 1., 1., 1., 1., 0., 0.]), array([0., 1., 0., 0., 1., 0., 0.]), array([1., 1., 0., 0., 1., 0., 1.]), array([1., 1., 0., 1., 0., 1., 1.]), array([1., 1., 0., 0., 1., 0., 0.]), array([0., 1., 1., 1., 1., 0., 0.]), array([1., 1., 1., 0., 1., 0., 1.]), array([0., 1., 1., 1., 1., 0., 1.]), array([1., 0., 1., 0., 1., 0., 0.]), array([1., 1., 1., 1., 0., 1., 1.]), array([1., 1., 1., 0., 1., 1., 0.])]

 And here is a binary string for each vector: 

y1_1: 1100100
y2_1: 1111100
y3_1: 0100100
y4_1: 1100101
y5_1: 1101011
y6_1: 1100100
y7_1: 0111100
y8_1: 1110101
y9_1: 0111101
y10_1: 1010100
y11_1: 1111011
y12_1: 1110110


LUT Implementation

In [7]:
# initialize the LUT
lut = {}

# consider the all-zero error vector
zero_error_vector = np.zeros(G.shape[1], dtype=int)
zero_syndrome = tuple(np.dot(zero_error_vector, H) % 2)
lut[zero_syndrome] = zero_error_vector.tolist()

# consider the n error vectors of weight 1
n = G.shape[1]  # number of columns in G

print("H matrix:")
print(H)

for i in range(n):
    error_vector = np.zeros(n, dtype=int)
    error_vector[i] = 1
    print("Error vector:")
    print(error_vector)

    # compute the syndrome s = e * H
    syndrome = tuple(np.dot(error_vector, H) % 2)
    print("Corresponding syndrom:")
    print(syndrome, "\n")
    # store the syndrome and error vector in the LUT
    lut[syndrome] = error_vector.tolist()

print("\n This is LUT:")
print(lut)

H matrix:
[[0 1 1]
 [1 0 0]
 [0 0 1]
 [1 1 1]
 [1 1 0]
 [1 0 1]
 [0 1 0]]
Error vector:
[1 0 0 0 0 0 0]
Corresponding syndrom:
(0, 1, 1) 

Error vector:
[0 1 0 0 0 0 0]
Corresponding syndrom:
(1, 0, 0) 

Error vector:
[0 0 1 0 0 0 0]
Corresponding syndrom:
(0, 0, 1) 

Error vector:
[0 0 0 1 0 0 0]
Corresponding syndrom:
(1, 1, 1) 

Error vector:
[0 0 0 0 1 0 0]
Corresponding syndrom:
(1, 1, 0) 

Error vector:
[0 0 0 0 0 1 0]
Corresponding syndrom:
(1, 0, 1) 

Error vector:
[0 0 0 0 0 0 1]
Corresponding syndrom:
(0, 1, 0) 


 This is LUT:
{(0, 0, 0): [0, 0, 0, 0, 0, 0, 0], (0, 1, 1): [1, 0, 0, 0, 0, 0, 0], (1, 0, 0): [0, 1, 0, 0, 0, 0, 0], (0, 0, 1): [0, 0, 1, 0, 0, 0, 0], (1, 1, 1): [0, 0, 0, 1, 0, 0, 0], (1, 1, 0): [0, 0, 0, 0, 1, 0, 0], (1, 0, 1): [0, 0, 0, 0, 0, 1, 0], (0, 1, 0): [0, 0, 0, 0, 0, 0, 1]}


This piece of code is implemented in order to recover the information vector from codeword.
Actually it works similar to gflineq(G',c',2) in Matlab.

In [8]:
def gf2_add(a, b):
    return np.bitwise_xor(a, b)

def gf2_multiply(a, b):
    return np.bitwise_and(a, b)

def gf2_solve(G, c):
    n, m = G.shape

    # augment the matrix G with vector c
    augmented_matrix = np.hstack((G, c.reshape(-1, 1)))

    # gaussian elimination in GF(2)
    for i in range(min(n, m)):
        pivot_row = next((j for j in range(i, n) if augmented_matrix[j, i] == 1), None)
        if pivot_row is None:
            raise ValueError("Matrix is not invertible")

        augmented_matrix[[i, pivot_row], :] = augmented_matrix[[pivot_row, i], :]

        for j in range(n):
            if j != i and augmented_matrix[j, i] == 1:
                augmented_matrix[j, :] = gf2_add(augmented_matrix[j, :], augmented_matrix[i, :])

    # back-substitution
    solution_GF2 = np.zeros(m, dtype=int)
    for i in range(min(n, m)-1, -1, -1):
        solution_GF2[i] = augmented_matrix[i, -1]
        for j in range(i + 1, m):
            if augmented_matrix[i, j] == 1:
                solution_GF2[i] = gf2_add(solution_GF2[i], gf2_multiply(augmented_matrix[i, j], solution_GF2[j]))

    return solution_GF2


In the for loop for each vector we calculated v1 by computing the syndrome and extracting the error vector, and calculating the codeword which is c1 = y1 + error_vector.

In [9]:
# initialize the decoded matrices
v1_decoded_matrices = []

print("H matrix:")
print(H)

# syndrome decoding for each y1_matrix
for i, y1_matrix in enumerate(y1_matrices):
    print("\n This is our y1:")
    print(y1_matrix)

    # compute the syndrome s = y1_matrix * H
    syndrome = np.dot(y1_matrix, H) % 2
    print("calculated syndrome:")
    print(syndrome)

    # obtain the corresponding error vector e from the LUT
    error_vector = lut[tuple(syndrome)]
    print("corresponding error vector:")
    print(error_vector)

    # obtain the received codeword c1 = y1 + e
    received_codeword = (y1_matrix + error_vector) % 2
    print("This is codeword")
    print(received_codeword)

    # make codeword items to integer items
    c = []
    for i in received_codeword:
      x = int(i)
      c.append(x)


    # obtain the corresponding information vector v
    v1_decoded_matrix = gf2_solve(G.T, np.array(c).T).astype(int)

    print("This is calculated v1:")
    print(v1_decoded_matrix)

    v1_decoded_matrices.append(np.array(v1_decoded_matrix))

# print the decoded matrices
for i, j in enumerate(v1_decoded_matrices, start=1):
    print(f"v{i}_decoded: {j}")

H matrix:
[[0 1 1]
 [1 0 0]
 [0 0 1]
 [1 1 1]
 [1 1 0]
 [1 0 1]
 [0 1 0]]

 This is our y1:
[1. 1. 0. 0. 1. 0. 0.]
calculated syndrome:
[0. 0. 1.]
corresponding error vector:
[0, 0, 1, 0, 0, 0, 0]
This is codeword
[1. 1. 1. 0. 1. 0. 0.]
This is calculated v1:
[1 0 1 1]

 This is our y1:
[1. 1. 1. 1. 1. 0. 0.]
calculated syndrome:
[1. 1. 1.]
corresponding error vector:
[0, 0, 0, 1, 0, 0, 0]
This is codeword
[1. 1. 1. 0. 1. 0. 0.]
This is calculated v1:
[1 0 1 1]

 This is our y1:
[0. 1. 0. 0. 1. 0. 0.]
calculated syndrome:
[0. 1. 0.]
corresponding error vector:
[0, 0, 0, 0, 0, 0, 1]
This is codeword
[0. 1. 0. 0. 1. 0. 1.]
This is calculated v1:
[1 0 1 0]

 This is our y1:
[1. 1. 0. 0. 1. 0. 1.]
calculated syndrome:
[0. 1. 1.]
corresponding error vector:
[1, 0, 0, 0, 0, 0, 0]
This is codeword
[0. 1. 0. 0. 1. 0. 1.]
This is calculated v1:
[1 0 1 0]

 This is our y1:
[1. 1. 0. 1. 0. 1. 1.]
calculated syndrome:
[1. 1. 1.]
corresponding error vector:
[0, 0, 0, 1, 0, 0, 0]
This is codeword
[1

Obtain vhat = (v_1)*(S_inverse)
First we calculated the inverse of matrix S then multiply S_inverse and v in GF(2)

In [11]:
def gf2_matrix_multiply(A, B):
    result = np.zeros_like(A, dtype=int)

    for i in range(A.shape[0]):
        for j in range(B.shape[1]):
            result[i, j] = np.bitwise_xor.reduce(gf2_multiply(A[i, :], B[:, j]))

    return result

matrix_A = np.array(v1_decoded_matrices, dtype=int)

# inverse of S
S_inv = inv(S)

matrix_B = np.array(S_inv, dtype=int)

# multiply matrices in GF(2)
result_matrix = gf2_matrix_multiply(matrix_A, matrix_B)

print("v1:")
print(matrix_A)
print("\nS inverse:")
print(matrix_B)
print("\nResult Matrix (GF(2)):")
print(result_matrix)


v:
[[1 0 1 1]
 [1 0 1 1]
 [1 0 1 0]
 [1 0 1 0]
 [1 0 0 1]
 [1 0 1 1]
 [1 1 1 1]
 [1 0 1 1]
 [0 1 0 1]
 [1 0 1 1]
 [0 1 1 0]
 [1 0 1 1]]

S inverse:
[[-1  1  0  0]
 [ 0  0  0  1]
 [ 0 -1  1  0]
 [ 1  0  0  0]]

Result Matrix (GF(2)):
[[0 0 1 0]
 [0 0 1 0]
 [1 0 1 0]
 [1 0 1 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 1 1]
 [0 0 1 0]
 [1 0 0 1]
 [0 0 1 0]
 [0 1 1 1]
 [0 0 1 0]]


Collect together all information vectors vhat, the applied the ASCII decoding to obtain the name of the city


1.   First we change the shape of v_hat and extract every paires of it. so it will be 6 pairs as v_hat has shape 12x4.

2.   Then for each pair flip them and then change the order of 2 vectors.
Now we can combine them together and calculate the decimal value of each pair which is 8 bit.

3.   Now we can find the corresponding char of the decimal value.





In [15]:
matrix_v = np.array(result_matrix)
print("This is V:")
print(matrix_v)
# reshape v to create pairs of vectors
pairs = matrix_v.reshape(-1, 2, matrix_v.shape[1])

# process each pair of vectors
result_word = ""
for pair in pairs:
    print("\n This pair:")
    print(pair)
    # reverse the bits of each vector from the right
    reversed_vectors = np.flip(pair, axis=1)
    print("Reserved vector:")
    print(reversed_vectors)

    reversed_vectors = np.flip(reversed_vectors, axis=0)

    print("Change the order of vectors:")
    print(reversed_vectors)

    # convert the reversed vectors to a single binary string
    binary_string = ''.join(map(str, reversed_vectors.flatten()))
    print("Combine:")
    print(binary_string)
    # convert the binary string to decimal and then to ASCII
    combined_decimal = int(binary_string, 2)
    print("Deecimal value:")
    print(combined_decimal)
    result_word += chr(combined_decimal)


This is V:
[[0 0 1 0]
 [0 0 1 0]
 [1 0 1 0]
 [1 0 1 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 1 1]
 [0 0 1 0]
 [1 0 0 1]
 [0 0 1 0]
 [0 1 1 1]
 [0 0 1 0]]

 This pair:
[[0 0 1 0]
 [0 0 1 0]]
Reserved vector:
[[0 1 0 0]
 [0 1 0 0]]
Change the order of vectors:
[[0 1 0 0]
 [0 1 0 0]]
Combine:
01000100
Deecimal value:
68

 This pair:
[[1 0 1 0]
 [1 0 1 0]]
Reserved vector:
[[0 1 0 1]
 [0 1 0 1]]
Change the order of vectors:
[[0 1 0 1]
 [0 1 0 1]]
Combine:
01010101
Deecimal value:
85

 This pair:
[[0 1 0 0]
 [0 0 1 0]]
Reserved vector:
[[0 0 1 0]
 [0 1 0 0]]
Change the order of vectors:
[[0 1 0 0]
 [0 0 1 0]]
Combine:
01000010
Deecimal value:
66

 This pair:
[[0 0 1 1]
 [0 0 1 0]]
Reserved vector:
[[1 1 0 0]
 [0 1 0 0]]
Change the order of vectors:
[[0 1 0 0]
 [1 1 0 0]]
Combine:
01001100
Deecimal value:
76

 This pair:
[[1 0 0 1]
 [0 0 1 0]]
Reserved vector:
[[1 0 0 1]
 [0 1 0 0]]
Change the order of vectors:
[[0 1 0 0]
 [1 0 0 1]]
Combine:
01001001
Deecimal value:
73

 This pair:
[[0 1 1 1]
 [0 0 1

Final result:

In [17]:
# print the result
print("City name:", result_word)

City name: DUBLIN
